# Site settings
title: Yannis Gkoumas
subtitle: Software Developer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: LinkedIn
github_username: GitHub
facebook_username: ygkoumas

#Post permalinks
permalink: /blog/:title/

# Build settings
markdown: kramdown

#add javascript
js: javascript/GithubCall.js
